### ISSUE TITLE
WebGl EXPORT

### ISSUE THREAD

**Issue by enama** [cmdr2/unity-remote-obj-loader#4]
I tried this code and work perfectly on the unity editor but when I try it on webgl doesn't work, I get the models from url, when I see the console I see that it find the obj and the mtl properly but when it start meshrender it send me this:
NullReferenceException

 
(Filename: currently not available on il2cpp Line: -1)

What can I do?

**Comment by cmdr2** [comment]
Hmm, can you please paste the full stack trace?

Thanks

**Comment by enama** [comment]
Hi, thanks for reading, I don't really know how to show you the full trace when I export to webgl, but I tried exporting for windows (.exe) and I'm getting a NullReferenceException, so here I get the full trace:

Mono path[0] = 'C:/Users/Usuario/Documents/object/obj_Data/Managed'
Mono path[1] = 'C:/Users/Usuario/Documents/object/obj_Data/Mono'
Mono config path = 'C:/Users/Usuario/Documents/object/obj_Data/Mono/etc'
PlayerConnection initialized from C:/Users/Usuario/Documents/object/obj_Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55408
Multi-casting "[IP] 192.168.56.1 [Port] 55408 [Flags] 2 [Guid] 2788255297 [EditorId] 3312948293 [Version] 1048832 [Id] WindowsPlayer(DESKTOP-N9II3SD) [Debug] 0" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55408]
PlayerConnection already initialized - listening to [0.0.0.0:55408]
Initialize engine version: 5.5.2f1 (3829d7f588f3)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 10.1]
    Renderer: NVIDIA Quadro FX 880M (ID=0xa3c)
    Vendor:   NVIDIA
    VRAM:     970 MB
    Driver:   21.21.13.4201
Begin MonoManager ReloadAssembly
Platform assembly: C:\Users\Usuario\Documents\object\obj_Data\Managed\UnityEngine.dll (this message is harmless)
Loading C:\Users\Usuario\Documents\object\obj_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: C:\Users\Usuario\Documents\object\obj_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading C:\Users\Usuario\Documents\object\obj_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: C:\Users\Usuario\Documents\object\obj_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading C:\Users\Usuario\Documents\object\obj_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: C:\Users\Usuario\Documents\object\obj_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading C:\Users\Usuario\Documents\object\obj_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: C:\Users\Usuario\Documents\object\obj_Data\Managed\UnityEngine.PlaymodeTestsRunner.dll (this message is harmless)
Loading C:\Users\Usuario\Documents\object\obj_Data\Managed\UnityEngine.PlaymodeTestsRunner.dll into Unity Child Domain
- Completed reload, in  0.668 seconds
Platform assembly: C:\Users\Usuario\Documents\object\obj_Data\Managed\System.Core.dll (this message is harmless)
Platform assembly: C:\Users\Usuario\Documents\object\obj_Data\Managed\System.dll (this message is harmless)
desktop: 1920x1080 60Hz; virtual: 1920x1080 at 0,0
<RI> Initializing input.

XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.856123 ms
NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Material:Internal_CreateWithShader (UnityEngine.Material,UnityEngine.Shader)
  at UnityEngine.Material..ctor (UnityEngine.Shader shader) [0x00009] in C:\buildslave\unity\build\artifacts\generated\common\runtime\ShaderBindings.gen.cs:313 
  at OBJ.GetMaterial (.MaterialData md) [0x00018] in C:\Users\Usuario\Documents\object\Assets\OBJ\src\OBJ.cs:191 
  at OBJ.Build () [0x00037] in C:\Users\Usuario\Documents\object\Assets\OBJ\src\OBJ.cs:214 
  at OBJ+<Load>c__Iterator0.MoveNext () [0x00209] in C:\Users\Usuario\Documents\object\Assets\OBJ\src\OBJ.cs:63 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00028] in C:\buildslave\unity\build\Runtime\Export\Coroutines.cs:17 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/ShaderBindings.gen.cs Line: 313)

**Comment by cmdr2** [comment]
Okay, so there's a chance that Unity is not including the required Shaders into your WebGL build, because Unity only includes a Shader if it is actually being used in the project at compile-time. This OBJ loader creates the material at run-time.

Can you try creating two Materials in your Unity project, and set the Shader dropdown on one of them to "Standard (Specular Setup)"? This should fool Unity into including those Shaders into the final build.

Please let me know if this helps.

Thanks
~cmdr2

**Comment by enama** [comment]
Hi, you were rigth about Standard shader, it solves the issue for .exe exportation .But when I tried it for WebGl I got this on the browser console:

Invoking error handler due to
Uncaught Assertion failed: s_GlobalMetadataHeader->sanity == 0xFAB11BAF, at: C:\Program Files\Unity\Editor\Data\il2cpp\libil2cpp\vm\MetadataCache.cpp,139,Initialize at Error
    at jsStackTrace (WebGl.js:1:19540)
    at stackTrace (WebGl.js:1:19711)
    at ___assert_fail (WebGl.js:1:227122)
    at app (WebGl.asm.js:21:324322)
    at Ntp (WebGl.asm.js:21:436351)
    at Hvp (WebGl.asm.js:21:475697)
    at MOa (WebGl.asm.js:12:210104)
    at IOa [Object.IOa] (WebGl.asm.js:12:205629)
    at callMain [Object.callMain] (WebGl.js:3:28953)
    at doRun (WebGl.js:3:29659)
    at blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3:29809
blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3 Uncaught Assertion failed: s_GlobalMetadataHeader->sanity == 0xFAB11BAF, at: C:\Program Files\Unity\Editor\Data\il2cpp\libil2cpp\vm\MetadataCache.cpp,139,Initialize at Error
    at jsStackTrace (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:19540)
    at stackTrace (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:19711)
    at ___assert_fail (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:227122)
    at app (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:21:324322)
    at Ntp (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:21:436351)
    at Hvp (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:21:475697)
    at MOa (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:12:210104)
    at Object.IOa [as _main] (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:12:205629)
    at Object.callMain (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3:28953)
    at doRun (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3:29659)
    at blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3:29809
UnityLoader.js:2 Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 469762048, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
UnityLoader.js:2 Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 469762048, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
Module.printErr @ UnityLoader.js:2
UnityLoader.js:1 Invoking error handler due to
Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 469762048, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (WebGl.js:1:19540)
    at stackTrace (WebGl.js:1:19711)
    at abort (WebGl.js:3:30573)
    at abortOnCannotGrowMemory (WebGl.js:1:20592)
    at enlargeMemory (WebGl.js:1:21037)
    at dynamicAlloc [Function.dynamicAlloc] (WebGl.js:1:9105)
    at _sbrk (WebGl.js:1:313354)
    at K8p (WebGl.asm.js:32:89365)
    at Ghq (WebGl.asm.js:32:350379)
    at vJb (WebGl.asm.js:9:400240)
    at uJb (WebGl.asm.js:9:397907)
    at mJb [Array.mJb] (WebGl.asm.js:9:393249)
    at Nmq (WebGl.asm.js:32:393956)
    at dynCall [Object.dynCall] (WebGl.js:1:7426)
    at handlerFunc [Object.handlerFunc] (WebGl.js:1:68176)
    at jsEventHandler (WebGl.js:1:64703)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3 Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 469762048, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:19540)
    at stackTrace (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:19711)
    at abort (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3:30573)
    at abortOnCannotGrowMemory (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:20592)
    at enlargeMemory (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:21037)
    at Function.dynamicAlloc [as alloc] (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:9105)
    at _sbrk (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:313354)
    at K8p (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32:89365)
    at Ghq (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32:350379)
    at vJb (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9:400240)
    at uJb (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9:397907)
    at Array.mJb (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9:393249)
    at Nmq (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32:393956)
    at Object.dynCall (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:7426)
    at Object.handlerFunc (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:68176)
    at jsEventHandler (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:64703)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
UnityLoader.js:2 124
UnityLoader.js:2 124
Module.printErr @ UnityLoader.js:2
UnityLoader.js:1 Invoking error handler due to
Uncaught abort(124) at Error
    at jsStackTrace (WebGl.js:1:19540)
    at stackTrace (WebGl.js:1:19711)
    at abort (WebGl.js:3:30573)
    at mvq [Array.mvq] (WebGl.asm.js:32:424357)
    at nJb [Array.nJb] (WebGl.asm.js:9:393733)
    at Nmq (WebGl.asm.js:32:393956)
    at dynCall [Object.dynCall] (WebGl.js:1:7426)
    at handlerFunc [Object.handlerFunc] (WebGl.js:1:68176)
    at jsEventHandler (WebGl.js:1:64703)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3 Uncaught abort(124) at Error
    at jsStackTrace (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:19540)
    at stackTrace (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:19711)
    at abort (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3:30573)
    at Array.mvq (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32:424357)
    at Array.nJb (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9:393733)
    at Nmq (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32:393956)
    at Object.dynCall (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:7426)
    at Object.handlerFunc (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:68176)
    at jsEventHandler (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:64703)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
http://localhost:8080/navargp/acceso/TemplateData/Logo.Light.png Failed to load resource: the server responded with a status of 404 (No Encontrado)
http://localhost:8080/navargp/acceso/TemplateData/ProgressFrame.Light.png Failed to load resource: the server responded with a status of 404 (No Encontrado)
barranavegacion.css Failed to load resource: the server responded with a status of 404 (No Encontrado)
UnityLoader.js:2 124
UnityLoader.js:2 124
Module.printErr @ UnityLoader.js:2
abort @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3
mvq @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32
nJb @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9
Nmq @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32
dynCall @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
handlerFunc @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
jsEventHandler @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
UnityLoader.js:1 Invoking error handler due to
Uncaught abort(124) at Error
    at jsStackTrace (WebGl.js:1:19540)
    at stackTrace (WebGl.js:1:19711)
    at abort (WebGl.js:3:30573)
    at mvq [Array.mvq] (WebGl.asm.js:32:424357)
    at nJb [Array.nJb] (WebGl.asm.js:9:393733)
    at Nmq (WebGl.asm.js:32:393956)
    at dynCall [Object.dynCall] (WebGl.js:1:7426)
    at handlerFunc [Object.handlerFunc] (WebGl.js:1:68176)
    at jsEventHandler (WebGl.js:1:64703)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3 Uncaught abort(124) at Error
    at jsStackTrace (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:19540)
    at stackTrace (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:19711)
    at abort (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3:30573)
    at Array.mvq (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32:424357)
    at Array.nJb (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9:393733)
    at Nmq (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32:393956)
    at Object.dynCall (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:7426)
    at Object.handlerFunc (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:68176)
    at jsEventHandler (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:64703)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
abort @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3
mvq @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32
nJb @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9
Nmq @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32
dynCall @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
handlerFunc @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
jsEventHandler @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
UnityLoader.js:2 124
UnityLoader.js:2 124
Module.printErr @ UnityLoader.js:2
abort @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3
mvq @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32
nJb @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9
Nmq @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32
dynCall @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
handlerFunc @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
jsEventHandler @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
UnityLoader.js:1 Invoking error handler due to
Uncaught abort(124) at Error
    at jsStackTrace (WebGl.js:1:19540)
    at stackTrace (WebGl.js:1:19711)
    at abort (WebGl.js:3:30573)
    at mvq [Array.mvq] (WebGl.asm.js:32:424357)
    at nJb [Array.nJb] (WebGl.asm.js:9:393733)
    at Nmq (WebGl.asm.js:32:393956)
    at dynCall [Object.dynCall] (WebGl.js:1:7426)
    at handlerFunc [Object.handlerFunc] (WebGl.js:1:68176)
    at jsEventHandler (WebGl.js:1:64703)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3 Uncaught abort(124) at Error
    at jsStackTrace (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:19540)
    at stackTrace (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:19711)
    at abort (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3:30573)
    at Array.mvq (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32:424357)
    at Array.nJb (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9:393733)
    at Nmq (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32:393956)
    at Object.dynCall (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:7426)
    at Object.handlerFunc (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:68176)
    at jsEventHandler (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:64703)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
abort @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3
mvq @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32
nJb @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9
Nmq @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32
dynCall @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
handlerFunc @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
jsEventHandler @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
UnityLoader.js:2 124
UnityLoader.js:2 124
Module.printErr @ UnityLoader.js:2
abort @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3
mvq @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32
nJb @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9
Nmq @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32
dynCall @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
handlerFunc @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
jsEventHandler @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
UnityLoader.js:1 Invoking error handler due to
Uncaught abort(124) at Error
    at jsStackTrace (WebGl.js:1:19540)
    at stackTrace (WebGl.js:1:19711)
    at abort (WebGl.js:3:30573)
    at mvq [Array.mvq] (WebGl.asm.js:32:424357)
    at nJb [Array.nJb] (WebGl.asm.js:9:393733)
    at Nmq (WebGl.asm.js:32:393956)
    at dynCall [Object.dynCall] (WebGl.js:1:7426)
    at handlerFunc [Object.handlerFunc] (WebGl.js:1:68176)
    at jsEventHandler (WebGl.js:1:64703)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3 Uncaught abort(124) at Error
    at jsStackTrace (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:19540)
    at stackTrace (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:19711)
    at abort (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3:30573)
    at Array.mvq (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32:424357)
    at Array.nJb (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9:393733)
    at Nmq (blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32:393956)
    at Object.dynCall (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:7426)
    at Object.handlerFunc (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:68176)
    at jsEventHandler (blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1:64703)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
abort @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:3
mvq @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32
nJb @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:9
Nmq @ blob:http://localhost:8080/46f46c86-e1ce-46a0-b8cb-ef67b2e5516c:32
dynCall @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
handlerFunc @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1
jsEventHandler @ blob:http://localhost:8080/d63b89be-955c-4d2f-9236-a0e8aeea2a0f:1

**Comment by cmdr2** [comment]
I have a feeling this new error is not related to OBJ. Does this error happen even when you disable the OBJ loader gameobject?

From what I see, this error happens due to mixed up versions of Unity files (old and new versions). Can you try removing the old build and compiling again? Maybe these are helpful:

https://forum.unity3d.com/threads/uncaught-assertion-failed-s_globalmetadataheader-metadatacache-cpp.439913/

http://answers.unity3d.com/questions/1226838/web-gl-failing-with-the-following-error-any-ideas.html

**Comment by cmdr2** [comment]
Closing since the original problem was solved, and the second problem doesn't appear to be related to this project (but a workaround has been suggested).
